### ISSUE TITLE
Suggestion: Adding Timer Functionality to IntesisHome Integration

### ISSUE THREAD

**Issue by kitopopo** [jnimmo/hass-intesishome#23]
Hello,

I’d like to propose a feature enhancement for the IntesisHome integration.

The official IntesisHome app includes the ability to use a timer for turning off air conditioning units. Would it be possible to implement this functionality in the current Home Assistant integration?

I believe having a shutdown timer as an additional option within the air conditioning interface in Home Assistant would be highly beneficial. However, I lack the expertise to implement it myself and wouldn’t know where to begin.

Does anyone feel capable of developing this feature or guiding its implementation? @jnimmo, @srkoster or @autumnwalker ? would certainly add value to the integration and make it more feature-complete compared to the official app.

Thank you in advance for your attention and for all the effort you’ve already invested in this integration!

Best regards,

**Comment by srkoster** [comment]
Hi @kitopopo ,

The IntesisHome entities are Home Assistant [climate](https://www.home-assistant.io/integrations/climate/) entities. There's no native support for timers in that entity, but this can be achieved using [automations](https://www.home-assistant.io/integrations/climate/#automation-examples).

For example

```
description: "Trigger Intesishome airconditioning and shutdown after 1 hour"
mode: single
triggers: []
conditions: []
actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 19
      hvac_mode: cool
    target:
      entity_id: climate.device_0226b4
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: climate.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: climate.device_0226b4

```
